# Generated by Django 5.2 on 2025-05-11 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EgitimMerkezi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('adres', models.TextField()),
                ('telefon', models.CharField(max_length=20)),
                ('konum', models.CharField(max_length=255)),
                ('istatistik_sef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istatistik_egitim_merkezleri', to=settings.AUTH_USER_MODEL)),
                ('mudur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudur_egitim_merkezleri', to=settings.AUTH_USER_MODEL)),
                ('sef_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sef1_egitim_merkezleri', to=settings.AUTH_USER_MODEL)),
                ('sef_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sef2_egitim_merkezleri', to=settings.AUTH_USER_MODEL)),
                ('sef_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sef3_egitim_merkezleri', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('kontenjan', models.PositiveIntegerField()),
                ('egitim_merkezi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egitim_takip.egitimmerkezi')),
            ],
        ),
        migrations.CreateModel(
            name='TesisImkani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yatakli_kontenjan', models.PositiveIntegerField()),
                ('yataksiz_kontenjan', models.PositiveIntegerField()),
                ('egitim_merkezi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='egitim_takip.egitimmerkezi')),
            ],
        ),
        migrations.CreateModel(
            name='Yemekhane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogun_adi', models.CharField(max_length=100)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egitim_takip.tesisimkani')),
            ],
        ),
    ]
