# Generated by Django 5.2 on 2025-05-11 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_takip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi', models.CharField(default='Eğitim Takip Sistemi', max_length=200)),
                ('meta_baslik', models.CharField(blank=True, max_length=200)),
                ('meta_aciklama', models.TextField(blank=True)),
                ('meta_etiketler', models.CharField(blank=True, max_length=300)),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('footer_yazi', models.CharField(blank=True, max_length=255)),
                ('iletisim_email', models.EmailField(blank=True, max_length=254)),
                ('iletisim_telefon', models.CharField(blank=True, max_length=20)),
                ('tema', models.CharField(choices=[('acik', 'Açık'), ('koyu', 'Koyu')], default='koyu', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('meta_description', models.TextField()),
                ('footer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Açık'), ('dark', 'Koyu')], default='light', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
