# Generated by Django 5.2 on 2025-05-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_takip', '0002_siteayar_sitesettings_themeconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteayar',
            options={'verbose_name': 'Site Ayarı', 'verbose_name_plural': 'Site Ayarları'},
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='footer_yazi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt bilgi yazısı'),
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Header logosu'),
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='iletisim_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='İletişim e-posta'),
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='iletisim_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='İletişim telefonu'),
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='meta_aciklama',
            field=models.TextField(blank=True, verbose_name='Meta açıklama'),
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='meta_baslik',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta başlık'),
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='meta_etiketler',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta etiketler'),
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='site_adi',
            field=models.CharField(default='Eğitim Takip Sistemi', max_length=200, verbose_name='Site adı'),
        ),
        migrations.AlterField(
            model_name='siteayar',
            name='tema',
            field=models.CharField(choices=[('acik', 'Açık'), ('koyu', 'Koyu')], default='koyu', max_length=10, verbose_name='Tema'),
        ),
    ]
