# Generated by Django 5.2 on 2025-05-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_takip', '0003_alter_siteayar_options_alter_siteayar_footer_yazi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
