# Generated by Django 5.2 on 2025-05-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim_takip', '0004_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgitimTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Eğitim Türü')),
                ('saat', models.PositiveIntegerField(verbose_name='Süre (saat)')),
            ],
        ),
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Eğitim Adı')),
                ('baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('egitim_merkezi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egitim_takip.egitimmerkezi')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egitim_takip.egitimturu')),
            ],
        ),
    ]
